name: Main branch

on:
  push:
    branches:
      - main

env:
  BRANCH_REF: ${{ github.ref }} # The fully-formed ref of the branch or tag that triggered the workflow run

jobs:

  build-docs:
    uses: ./.github/workflows/docs.yml

  linters:
    uses: ./.github/workflows/linters.yml

  tests-standard:
    uses: ./.github/workflows/tests-standard.yml

  tests-premium:
    uses: ./.github/workflows/tests-premium.yml

  tests-ultimate:
    uses: ./.github/workflows/tests-ultimate.yml