name: Release Please

on:
  workflow_call:

permissions:
  contents: write
  packages: write
  pull-requests: write

# Release-Please creates automatic PRs with the next release based on the Commit history, these PRs will show the next
# version to be created and the updated CHANGELOG.md content

# When merged in by Maintainers it will automatically bump the version and create the new release
jobs:
  release-please:
    runs-on: ubuntu-latest
    # Map step outputs to job outputs
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python
          token: ${{ secrets.RP_PAT }}
          # Default GITHUB_TOKEN does not have permission to trigger other Workflows
          # RELEASE_PLEASE_TOKEN is a fine-grained PAT associated with the gitlabform organisation: expires 15/04/25


